#!/usr/bin/env bash
#a Bash script that will display information about subdomains.
domain="$1"
subdomain="$2"

pprintDom () {
	dig "$1.$2" | grep -A1 'ANSWER SECTION' | awk 'NR==2' | awk '{sub(/\..*$/, "", $1); print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 1 ]; then
	for subs in www lb-01 web-01 web-02
	do
		pprintDom "$subs" "$1"
	done
else
	pprintDom "$subdomain" "$domain"
fi
