#!/usr/bin/env bash
# Check if the number of params is less then 4

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning params to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_path="$4"

# Constructing the scp command with necessary options
scp -o StrictHostKeyChecking=no -i "$ssh_path" "$file_path" "$username@$server_ip":~
