#!/usr/bin/env bash
# configuring the web server
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    # Add the custom header
    add_header X-Served-By $hostname;

    location / {
        return 200 "Hello World!\n";
    }
}
