#!/usr/bin/env bash
# Let's see if nginx is installed and if not lets install it
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default
service restart
