#!/usr/bin/env bash
# Making the fix short and sweet
sudo apt-get install -y nginx
sudo sed -i 's/80 default_server/80 default_server\n        location \/ {\n      \n           return 200;\n        }/' /etc/nginx/sites-available/default
sudo service nginx stop
