#!/usr/bin/env bash
# Handling SIGTERM signal

# Function to handle SIGTERM signal

terminate_handler()
{
	echo "I am invincible!!!"
	exit 0
}
# Set up trap to catch SIGTERM and call the terminate_handler function
trap terminate_handler SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done

