#!/usr/bin/env bash
# Fizz for muls of 3, buzz for 5 fizzbuzz for both

i=1

while [ $i -lt 101 ]; do
        if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
        then
                echo "FizzBuzz"
        elif [ $((i % 3)) -eq 0 ]
        then
                echo "Fizz"
        elif [ $((i % 5)) -eq 0 ]
        then
                echo "Buzz"
        else
                echo "$i"
        fi
        ((i++))
done
