#!/usr/bin/env bash
# Displaying contents of the file /etc/passwd, using the while loop + IFS

pass_file="/etc/passwd"

while IFS=: read -r username _ uid gid info home shell; do
	user_info=$(grep -w "^$uid" /etc/passwd | cut -d: -f5)
	echo "The user $username is part of the $gid gang,"
	echo "lives in $home and rides $shell."
	echo "User ID's place is protected by the passcode $info,"
	echo "more info about the user here: $user_info"
	echo "-------------------------"
done < "$pass_file"
