#!/usr/bin/env bash
# configures the localhost file

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
