#!/usr/bin/env bash
# fixing debugging issue

# Run the Docker container in detached mode
docker run -p 8080:80 -d holbertonschool/265-0

# Connect to the running container in interactive mode
docker exec -it "$(docker ps -q)" /bin/bash

# If the web server is not running, start it
service nginx start

# Check if the web server is binding to port 80
netstat -tulpn | grep :80

# If not, there might be a configuration issue, check the Nginx configuration
cat /etc/nginx/nginx.conf
cat /etc/nginx/sites-available/default

# If you find any issues, fix the configuration and restart the Nginx service
service nginx restart

# Exit the container
exit
