#!/usr/bin/env bash
# fixing debugging issue

# Run the Docker container in detached mode
docker run -p 8080:80 -d holbertonschool/265-0

# Connect to the running container in interactive mode
docker exec -it "$(docker ps -q)" /bin/bash
