#!/usr/bin/env bash
# set a nginx user to nginx

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf

# updating nginx configuration to listen to all active ports on 8080
sed -i 's/^listen .*/listen 8080 default_server;/g' /etc/nginx/sites-available/default

sudo service nginx restart
